name: Cron Exec

on:
  workflow_dispatch:
  # schedule:
  #   # triggers everyday 08:00
  #   - cron '0 8 * * *'

env:
  CHAT_ID: ${{ secrets.CHAT_ID }}
  TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
  IMAGE: "ghcr.io/64j0/daily-verse-telegram-bot:2023.07.15-00.42.24"
  
jobs:
  run-container:
    name: Run Container
    runs-on: ubuntu-22.04
    steps:
      - name: Pull the container
        run: docker pull "${IMAGE}"
      - name: Run the container
        run: |
          docker run \
            -e "CHAT_ID=${CHAT_ID}" \
            -e "TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}" \
            "${IMAGE}"
        
